<a href="https://colab.research.google.com/github/wtryab-re/data-preprocessing/blob/main/Handling_Imbalanced_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Where there are more of one target variable than another that dataset is imbalanced and model gets biased.

Oversampling, undersampling and SMOTE

In [24]:
!pip install -q seaborn pandas numpy imbalanced-learn

In [26]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE, RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

Check imbalance

Apply undersampling, oversampling, SMOTE

Work only on the TRAIN data

###Dataset load

In [20]:
df = load_breast_cancer(as_frame=True).frame
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

###train test split

In [28]:
X=df.drop('target',axis=1)
y=df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((455, 30), (114, 30), (455,), (114,))

###Target Distribution

In [33]:
y_train.value_counts(normalize=True)
df["target"].value_counts(normalize=True)
#60% of target vals are true
#40% is false

#imbalanaced

target
1    0.627417
0    0.372583
Name: proportion, dtype: float64

Undersampling decreases the amount of the majority class to the amount of the minority class.

ex: true = 200, false = 50 -> true = 50, false = 50

Oversampling increases the amount of the minority class to the amount of the majority class.

ex: true = 200, false = 50 -> true = 250, false = 250

Any sort of oversampling and undersampling should be done BEFORE train test split. because data leakage

#Random Under Sampling on train set

##Before Undersampling

In [43]:
y_train.shape

(455,)

In [46]:
y_train.value_counts(normalize=True, ).round(3)

target
1    0.626
0    0.374
Name: proportion, dtype: float64

##After Undersampling

In [47]:
under_sampled = RandomUnderSampler(random_state=42)

In [35]:
X_us, y_us = under_sampled.fit_resample(X_train, y_train)

In [49]:
y_us.value_counts(normalize=True, ).round(3)

target
0    0.5
1    0.5
Name: proportion, dtype: float64

#Random Oversampling

##Before oversampling

In [50]:
y_train.value_counts(normalize=True, ).round(3)

target
1    0.626
0    0.374
Name: proportion, dtype: float64

In [53]:
y_train.shape

(455,)

##After Oversampling

In [51]:
over_sampler = RandomOverSampler(random_state=42)

In [54]:
X_os, y_os = over_sampler.fit_resample(X_train, y_train)
y_os.shape

(570,)

In [55]:
y_os.value_counts(normalize=True, ).round(3)

target
1    0.5
0    0.5
Name: proportion, dtype: float64

#SMOTE - Synthetic Minority Over-Sampling Technique

Creates synthetic values between the data points instead of complete copies of minority class, which is what oversampling does.

###Before Smote

In [56]:
y_train.value_counts(normalize=True, ).round(3)

target
1    0.626
0    0.374
Name: proportion, dtype: float64

###After SMOTE

In [57]:
smote = SMOTE(random_state=42)

In [58]:
X_sm, y_sm = smote.fit_resample(X_train, y_train)
y_sm.shape

(570,)

In [60]:
y_sm.value_counts(normalize=True, ).round(3)

target
1    0.5
0    0.5
Name: proportion, dtype: float64

In [62]:
# a sample of the new samples created in X_sm that is NOT in X_train
X_sm.loc[~X_sm.index.isin(X_train.index)].head(2)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
1,20.18,19.54,133.8,1250.0,0.1133,0.1489,0.2133,0.12590,0.1724,0.06053,...,22.03,25.07,146.0,1479.0,0.1665,0.2942,0.5308,0.2173,0.3032,0.08075
14,19.89,20.26,130.5,1214.0,0.1037,0.1310,0.1411,0.09431,0.1802,0.06188,...,23.73,25.23,160.5,1646.0,0.1417,0.3309,0.4185,0.1613,0.2549,0.09136

  Accuracy is not a good metric if the dataset is imbalanced.

  Precision, recall, f1-score are much better.

Use oversampling when you have a small overall dataset and cannot afford to lose majority class information.

 Use undersampling when your dataset is massive and computational resources or training time are limited.

 Use SMOTE when your minority class features are continuous and you want to introduce structural diversity without duplicating data