<a href="https://colab.research.google.com/github/wtryab-re/data-preprocessing/blob/main/Train_Test_Split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Imports and Installs

In [ ]:
!pip install -q numpy pandas matplotlib seaborn scikit-learn

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [ ]:
np.random.seed(42)
pd.set_option('display.max_columns', None)

#Data processing

train and test sets should be made BEFORE any preprocessing

In [ ]:
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.shape

(891, 15)

#Drop Redundant Columns

alive and survived are redundant, drop one of em

In [ ]:
df.drop("alive", inplace=True, axis=1)

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,True

#Drop rows with missing target value!!!

In [ ]:
df.loc[len(df)] = np.random.randint(0, 10, size=14)
df.iat[891, 0]= np.nan
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone
887,1.0,1,female,19.0,0,0,30.00,S,First,woman,0,B,Southampton,1
888,0.0,3,female,NaN,1,2,23.45,S,Third,woman,0,NaN,Southampton,0
889,1.0,1,male,26.0,0,0,30.00,C,First,man,1,C,Cherbourg,1
890,0.0,3,male,32.0,0,0,7.75,Q,Third,man,1,NaN,Queenstown,1
891,NaN,3,7,4.0,6,9,2.00,6,7,4,3,7,7,2

In [ ]:
df.dropna(subset=["survived"],inplace=True)

In [ ]:
df.shape

(891, 14)

In [ ]:
df.tail(1)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone
890,0.0,3,male,32.0,0,0,7.75,Q,Third,man,1,NaN,Queenstown,1

##Train set, test set, validation set

In [ ]:
X = df.drop('survived', axis=1)
y = df['survived']

In [ ]:
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
X_train.shape

(712, 13)

In [ ]:
X_test.shape

(179, 13)

In [ ]:
y_train.shape

(712,)

In [ ]:
y_test.shape

(179,)

In [ ]:
y.nunique()
y.value_counts(normalize=True)

survived
0.0    0.616162
1.0    0.383838
Name: proportion, dtype: float64